# Model arguments
model_name_or_path: FreedomIntelligence/HuatuoGPT-o1-7B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: ./data/xpert_usmle
dataset_configs:
- all
# Num processes is less by 1 as vLLM is using 1 GPU
num_processes: 7

# GRPO trainer config
bf16: true
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.4
do_eval: false
eval_strategy: "no"
eval_steps: 100
gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: HuatuoGPT-o1-7B-xpert_usmle-GRPO
hub_strategy: every_save
learning_rate: 2.0e-05
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 1024
max_completion_length: 8192
max_steps: -1
num_generations: 3
num_train_epochs: 6
output_dir: data/HuatuoGPT-o1-7B-xpert_usmle-GRPO
overwrite_output_dir: true
per_device_eval_batch_size: 4   
per_device_train_batch_size: 2
push_to_hub: no
report_to:
- wandb
save_strategy: "epoch"
seed: 42
warmup_ratio: 0.1
cosine_max_len: 8192
